Repository AY1920S2-CS2103T-W17-2/main, pull requests merged in 2020-04, with the labels that each got.

#312 Fix JavaFX dependency issue
  build.gradle
Labels: severity.High, type.Bug

#319 Update UI.png
  README.adoc
  docs/UserGuide.adoc
  docs/images/Ui.png
  docs/images/View.png
Labels: priority.High, type.Task

#315 Support case-insensitive correction by default
  src/main/java/com/notably/logic/correction/AbsolutePathCorrectionEngine.java
  src/main/java/com/notably/logic/correction/StringCorrectionEngine.java
  src/main/java/com/notably/logic/correction/distance/LevenshteinDistanceCalculator.java
  src/test/java/com/notably/logic/correction/AbsolutePathCorrectionEngineTest.java
  src/test/java/com/notably/logic/correction/StringCorrectionEngineTest.java
  src/test/java/com/notably/logic/correction/distance/LevenshteinDistanceCalculatorTest.java
Labels: priority.Medium, type.Enhancement

#311 Implement dynamic-suggestions feature [View]
  src/main/java/com/notably/MainApp.java
  src/main/java/com/notably/view/MainWindow.java
  src/main/java/com/notably/view/SuggestionsWindowView.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/NotablyTheme.css
  src/main/resources/view/SuggestionsWindowView.fxml
Labels: priority.High, type.Enhancement

#321 Support forward-matching during path correction
  src/main/java/com/notably/logic/correction/AbsolutePathCorrectionEngine.java
  src/main/java/com/notably/logic/parser/DeleteCommandParser.java
  src/main/java/com/notably/logic/parser/NewCommandParser.java
  src/main/java/com/notably/logic/parser/OpenCommandParser.java
  src/main/java/com/notably/logic/parser/suggestion/OpenSuggestionCommandParser.java
  src/test/java/com/notably/logic/correction/AbsolutePathCorrectionEngineTest.java
Labels: priority.High, type.Enhancement

#328 Catch title exception
  src/main/java/com/notably/logic/parser/NewCommandParser.java
Labels: priority.High, type.Enhancement

#331 Change response text for edit and exit command
  src/main/java/com/notably/logic/commands/suggestion/EditSuggestionCommand.java
  src/main/java/com/notably/logic/commands/suggestion/ExitSuggestionCommand.java
  src/test/java/com/notably/logic/commands/suggestion/EditSuggestionCommandTest.java
  src/test/java/com/notably/logic/commands/suggestion/ExitSuggestionCommandTest.java
  src/test/java/com/notably/logic/suggestion/SuggestionEngineImplTest.java
Labels: priority.High, type.Enhancement

#327 Fix path correction bug
  src/main/java/com/notably/logic/correction/AbsolutePathCorrectionEngine.java
  src/test/java/com/notably/logic/correction/AbsolutePathCorrectionEngineTest.java
Labels: severity.High, type.Bug

#326 Fix wrong image URLs
  README.adoc
  docs/UserGuide.adoc
Labels: severity.High, type.Bug

#261 Add DeleteSuggestionCommandParser and DeleteSuggestionCommandParserTest
  src/main/java/com/notably/logic/parser/suggestion/DeleteSuggestionCommandParser.java
  src/main/java/com/notably/logic/suggestion/SuggestionEngineImpl.java
  src/test/java/com/notably/logic/parser/suggestion/DeleteSuggestionCommandParserTest.java
  src/test/java/com/notably/logic/suggestion/SuggestionEngineImplTest.java
Labels: priority.High, status.Ongoing, type.Enhancement

#332 Persistent lastOpenedPath
  src/main/java/com/notably/MainApp.java
  src/main/java/com/notably/logic/LogicManager.java
  src/main/java/com/notably/model/block/BlockModelImpl.java
  src/main/java/com/notably/model/util/SampleDataUtil.java
  src/main/java/com/notably/storage/BlockStorage.java
  src/main/java/com/notably/storage/JsonBlockStorage.java
  src/main/java/com/notably/storage/JsonSerializableBlockModel.java
  src/main/java/com/notably/storage/JsonSerializableBlockTree.java
  src/main/java/com/notably/storage/Storage.java
  src/main/java/com/notably/storage/StorageManager.java
  src/main/java/com/notably/view/SideBarTreeView.java
  src/test/data/JsonBlockStorageTest/invalidAndValidBlockData.json
  src/test/data/JsonBlockStorageTest/invalidBlockData.json
  src/test/data/JsonBlockStorageTest/notJsonFormatBlockData.json
  src/test/data/JsonSerializableBlockModelTest/blankDataInvalidPathBlockData.json
  src/test/data/JsonSerializableBlockModelTest/duplicateBlockData.json
  src/test/data/JsonSerializableBlockModelTest/invalidBlockData.json
  src/test/data/JsonSerializableBlockModelTest/missingPathBlockData.json
  src/test/data/JsonSerializableBlockModelTest/pathDoesntExistBlockData.json
  src/test/data/JsonSerializableBlockModelTest/typicalBlockData.json
  src/test/java/com/notably/storage/JsonBlockStorageTest.java
  src/test/java/com/notably/storage/JsonSerializableBlockModelTest.java
  src/test/java/com/notably/storage/JsonSerializableBlockTreeTest.java
  src/test/java/com/notably/storage/StorageManagerTest.java
  src/test/java/com/notably/testutil/TypicalBlockModel.java
Labels: priority.Medium, status.Ongoing, type.Enhancement

#334 Fix Search.png in demo
  docs/images/demo/Search.png
Labels: severity.High, type.Bug

#335 Update clear suggestions
  src/main/java/com/notably/logic/commands/suggestion/DeleteSuggestionCommand.java
  src/main/java/com/notably/logic/commands/suggestion/OpenSuggestionCommand.java
  src/main/java/com/notably/logic/suggestion/SuggestionEngineImpl.java
Labels: priority.High, type.Enhancement

#325 Update User guide (Delete feature)
  docs/UserGuide.adoc
Labels: priority.High, status.Ongoing, type.Task

#306 Improve UG features information
  docs/UserGuide.adoc
Labels: priority.Medium, status.Ongoing, type.Task

#341 Update UG for Mock PE
  docs/UserGuide.adoc
  docs/images/IntroToNotably.png
  docs/images/Legends.png
  docs/images/Ui.png
Labels: priority.High, type.Task

#337 Fix empty string as path bug
  src/main/java/com/notably/commons/path/AbsolutePath.java
  src/main/java/com/notably/commons/path/RelativePath.java
Labels: severity.High, type.Bug

#379 Update parse exception message for invalid path
  src/main/java/com/notably/logic/parser/suggestion/DeleteSuggestionCommandParser.java
  src/main/java/com/notably/logic/parser/suggestion/OpenSuggestionCommandParser.java
  src/test/java/com/notably/logic/parser/suggestion/DeleteSuggestionCommandParserTest.java
  src/test/java/com/notably/logic/parser/suggestion/OpenSuggestionCommandParserTest.java
  src/test/java/com/notably/logic/suggestion/SuggestionEngineImplTest.java
Labels: priority.High, type.Enhancement

#386 Setup coverage reporting to codecov
  .travis.yml
  build.gradle
Labels: priority.High, type.Enhancement

#382 Move responseText to ViewStateModel
  src/main/java/com/notably/model/ModelManager.java
  src/main/java/com/notably/model/suggestion/SuggestionModel.java
  src/main/java/com/notably/model/suggestion/SuggestionModelImpl.java
  src/main/java/com/notably/model/viewstate/ViewStateModel.java
  src/main/java/com/notably/model/viewstate/ViewStateModelImpl.java
Labels: priority.High, type.Enhancement

#387 Add codecov badge to README
  README.adoc
Labels: priority.Medium, type.Enhancement

#390 Update TypicalBlockModel to enable standardised BlockModel-related testing
  src/test/java/com/notably/testutil/TypicalBlockModel.java
Labels: priority.High, type.Task

#391 Fix forward matching bugs
  src/main/java/com/notably/logic/correction/AbsolutePathCorrectionEngine.java
  src/test/java/com/notably/logic/correction/AbsolutePathCorrectionEngineTest.java
Labels: severity.High, type.Bug

#394 Make CorrectionEngine returns a list of results
  src/main/java/com/notably/logic/correction/AbsolutePathCorrectionEngine.java
  src/main/java/com/notably/logic/correction/CorrectionResult.java
  src/main/java/com/notably/logic/correction/StringCorrectionEngine.java
  src/main/java/com/notably/logic/parser/DeleteCommandParser.java
  src/main/java/com/notably/logic/parser/NotablyParser.java
  src/main/java/com/notably/logic/parser/OpenCommandParser.java
  src/main/java/com/notably/logic/parser/suggestion/DeleteSuggestionCommandParser.java
  src/main/java/com/notably/logic/parser/suggestion/OpenSuggestionCommandParser.java
  src/main/java/com/notably/logic/suggestion/SuggestionEngineImpl.java
  src/test/java/com/notably/logic/correction/AbsolutePathCorrectionEngineTest.java
  src/test/java/com/notably/logic/correction/StringCorrectionEngineTest.java
Labels: priority.High, type.Enhancement

#395 Fix styling error for response text
  src/main/resources/view/NotablyTheme.css
Labels: priority.High, type.Enhancement

#397 Move correction engine creation out of CommandParsers
  src/main/java/com/notably/logic/parser/DeleteCommandParser.java
  src/main/java/com/notably/logic/parser/NotablyParser.java
  src/main/java/com/notably/logic/parser/OpenCommandParser.java
  src/main/java/com/notably/logic/parser/suggestion/DeleteSuggestionCommandParser.java
  src/main/java/com/notably/logic/parser/suggestion/OpenSuggestionCommandParser.java
  src/main/java/com/notably/logic/suggestion/SuggestionEngineImpl.java
  src/test/java/com/notably/logic/parser/suggestion/DeleteSuggestionCommandParserTest.java
  src/test/java/com/notably/logic/parser/suggestion/OpenSuggestionCommandParserTest.java
Labels: priority.Medium, type.Task

#405 Revamp Path's equal function to case insensitive
  src/main/java/com/notably/commons/path/AbsolutePath.java
  src/main/java/com/notably/commons/path/RelativePath.java
  src/test/java/com/notably/commons/path/AbsolutePathTest.java
  src/test/java/com/notably/commons/path/RelativePathTest.java
Labels: priority.High, type.Enhancement

#402 Implementation of EditCurrentBody in LogicManager.
  src/main/java/com/notably/logic/Logic.java
  src/main/java/com/notably/logic/LogicManager.java
  src/main/java/com/notably/logic/exceptions/EditBlockBodyException.java
  src/test/java/com/notably/logic/LogicManagerTest.java
Labels: priority.High, type.Task

#408 Create Flag for Block Editability.
  src/main/java/com/notably/model/ModelManager.java
  src/main/java/com/notably/model/viewstate/BlockEditFlagModel.java
  src/main/java/com/notably/model/viewstate/HelpFlagModel.java
  src/main/java/com/notably/model/viewstate/ViewStateModel.java
  src/main/java/com/notably/model/viewstate/ViewStateModelImpl.java
  src/test/java/com/notably/model/viewstate/ViewStateModelTest.java
Labels: priority.High

#403 Make SugCmdParser for new, help, exit, and error command
  src/main/java/com/notably/logic/commands/suggestion/DeleteSuggestionCommand.java
  src/main/java/com/notably/logic/commands/suggestion/EditSuggestionCommand.java
  src/main/java/com/notably/logic/commands/suggestion/ErrorSuggestionCommand.java
  src/main/java/com/notably/logic/commands/suggestion/ExitSuggestionCommand.java
  src/main/java/com/notably/logic/commands/suggestion/HelpSuggestionCommand.java
  src/main/java/com/notably/logic/commands/suggestion/NewSuggestionCommand.java
  src/main/java/com/notably/logic/commands/suggestion/OpenSuggestionCommand.java
  src/main/java/com/notably/logic/commands/suggestion/SearchSuggestionCommand.java
  src/main/java/com/notably/logic/parser/suggestion/DeleteSuggestionCommandParser.java
  src/main/java/com/notably/logic/parser/suggestion/EditSuggestionCommandParser.java
  src/main/java/com/notably/logic/parser/suggestion/ErrorSuggestionCommandParser.java
  src/main/java/com/notably/logic/parser/suggestion/ExitSuggestionCommandParser.java
  src/main/java/com/notably/logic/parser/suggestion/HelpSuggestionCommandParser.java
  src/main/java/com/notably/logic/parser/suggestion/NewSuggestionCommandParser.java
  src/main/java/com/notably/logic/parser/suggestion/OpenSuggestionCommandParser.java
  src/main/java/com/notably/logic/parser/suggestion/SuggestionCommandParser.java
  src/main/java/com/notably/logic/suggestion/SuggestionEngineImpl.java
  src/test/java/com/notably/logic/commands/suggestion/DeleteSuggestionCommandTest.java
  src/test/java/com/notably/logic/commands/suggestion/EditSuggestionCommandTest.java
  src/test/java/com/notably/logic/commands/suggestion/ErrorSuggestionCommandTest.java
  src/test/java/com/notably/logic/commands/suggestion/ExitSuggestionCommandTest.java
  src/test/java/com/notably/logic/commands/suggestion/HelpSuggestionCommandTest.java
  src/test/java/com/notably/logic/commands/suggestion/NewSuggestionCommandTest.java
  src/test/java/com/notably/logic/commands/suggestion/OpenSuggestionCommandTest.java
  src/test/java/com/notably/logic/commands/suggestion/SearchSuggestionCommandTest.java
  src/test/java/com/notably/logic/parser/suggestion/DeleteSuggestionCommandParserTest.java
  src/test/java/com/notably/logic/parser/suggestion/OpenSuggestionCommandParserTest.java
  src/test/java/com/notably/logic/suggestion/SuggestionEngineImplTest.java
Labels: priority.High, type.Enhancement

#413 Allow symbols in Title
  src/main/java/com/notably/model/block/Title.java
  src/test/data/JsonBlockStorageTest/invalidAndValidBlockData.json
  src/test/data/JsonBlockStorageTest/invalidBlockData.json
  src/test/data/JsonSerializableBlockModelTest/invalidBlockData.json
  src/test/java/com/notably/model/block/TitleTest.java
  src/test/java/com/notably/storage/JsonAdaptedBlockTreeItemTest.java
Labels: priority.Medium, status.Ongoing, type.Enhancement

#411 Change Title object comparison to case-insensitive
  src/main/java/com/notably/model/block/Title.java
  src/test/java/com/notably/model/block/TitleTest.java
Labels: priority.Medium, status.Ongoing, type.Enhancement

#419 Update valid path criteria
  src/main/java/com/notably/commons/path/AbsolutePath.java
  src/main/java/com/notably/commons/path/RelativePath.java
  src/main/java/com/notably/logic/commands/NewCommand.java
  src/main/java/com/notably/logic/parser/NewCommandParser.java
  src/main/java/com/notably/model/block/BlockModelImpl.java
  src/main/java/com/notably/model/util/SampleDataUtil.java
  src/main/java/com/notably/storage/JsonSerializableBlockModel.java
  src/test/java/com/notably/commons/path/AbsolutePathTest.java
  src/test/java/com/notably/commons/path/RelativePathTest.java
  src/test/java/com/notably/model/block/BlockModelTest.java
  src/test/java/com/notably/testutil/TypicalBlockModel.java
Labels: priority.High, type.Task

#421 Remove Edit Command parser
  src/main/java/com/notably/logic/commands/EditCommand.java
  src/main/java/com/notably/logic/parser/EditCommandParser.java
  src/main/java/com/notably/logic/parser/NotablyParser.java
Labels: priority.High, type.Enhancement

#422 Initialize codecov.yml
  codecov.yml
Labels: priority.Medium, type.Task

#418 Fix bugs in SugCmdParsers
  src/main/java/com/notably/logic/parser/suggestion/DeleteSuggestionCommandParser.java
  src/main/java/com/notably/logic/parser/suggestion/ErrorSuggestionCommandParser.java
  src/main/java/com/notably/logic/parser/suggestion/NewSuggestionCommandParser.java
  src/main/java/com/notably/logic/parser/suggestion/OpenSuggestionCommandParser.java
  src/main/java/com/notably/logic/suggestion/SuggestionEngineImpl.java
  src/test/java/com/notably/logic/parser/suggestion/DeleteSuggestionCommandParserTest.java
Labels: severity.High, type.Bug

#424 Fix case-insensitive integration bug in CorrectionEngine
  src/main/java/com/notably/logic/correction/AbsolutePathCorrectionEngine.java
  src/main/java/com/notably/logic/correction/StringCorrectionEngine.java
  src/test/java/com/notably/logic/correction/AbsolutePathCorrectionEngineTest.java
  src/test/java/com/notably/logic/correction/StringCorrectionEngineTest.java
Labels: severity.High, type.Bug

#427 Add default body content for root block
  src/main/java/com/notably/model/block/BlockImpl.java
  src/main/java/com/notably/model/block/BlockTreeItemImpl.java
  src/test/java/com/notably/model/block/BlockTreeTest.java
Labels: priority.Medium, status.Ongoing, type.Enhancement

#385 Create Sug Test Util Class to remove code duplication
  src/main/java/com/notably/logic/commands/suggestion/DeleteSuggestionCommand.java
  src/main/java/com/notably/logic/commands/suggestion/OpenSuggestionCommand.java
  src/main/java/com/notably/logic/commands/suggestion/SearchSuggestionCommand.java
  src/main/java/com/notably/logic/parser/suggestion/NewSuggestionCommandParser.java
  src/main/java/com/notably/model/suggestion/SuggestionItemImpl.java
  src/test/java/com/notably/logic/commands/suggestion/DeleteSuggestionCommandTest.java
  src/test/java/com/notably/logic/commands/suggestion/OpenSuggestionCommandTest.java
  src/test/java/com/notably/logic/commands/suggestion/SearchSuggestionCommandTest.java
  src/test/java/com/notably/logic/parser/suggestion/DeleteSuggestionCommandParserTest.java
  src/test/java/com/notably/logic/parser/suggestion/EditSuggestionCommandParserTest.java
  src/test/java/com/notably/logic/parser/suggestion/ErrorSuggestionCommandParserTest.java
  src/test/java/com/notably/logic/parser/suggestion/ExitSuggestionCommandParserTest.java
  src/test/java/com/notably/logic/parser/suggestion/HelpSuggestionCommandParserTest.java
  src/test/java/com/notably/logic/parser/suggestion/NewSuggestionCommandParserTest.java
  src/test/java/com/notably/logic/parser/suggestion/OpenSuggestionCommandParserTest.java
  src/test/java/com/notably/logic/parser/suggestion/SuggestionCommandParserTestUtil.java
  src/test/java/com/notably/logic/suggestion/SuggestionEngineImplTest.java
  src/test/java/com/notably/logic/suggestion/SuggestionTestUtil.java
Labels: priority.High, status.Ongoing, type.Enhancement

#416 Feature block content edit view [View]
  src/main/java/com/notably/logic/commands/EditCommand.java
  src/main/java/com/notably/view/MainWindow.java
  src/main/java/com/notably/view/blockcontent/BlockContent.java
  src/main/java/com/notably/view/blockcontent/BlockContentDisplayView.java
  src/main/java/com/notably/view/blockcontent/BlockContentEditView.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/NotablyTheme.css
  src/main/resources/view/blockcontent/BlockContentEditView.fxml
Labels: priority.High, status.Ongoing, type.Enhancement

#428 Create SearchSuggestionCommandParser
  src/main/java/com/notably/logic/parser/suggestion/SearchSuggestionCommandParser.java
  src/main/java/com/notably/logic/suggestion/SuggestionEngineImpl.java
  src/test/java/com/notably/logic/parser/suggestion/SearchSuggestionCommandParserTest.java
  src/test/java/com/notably/logic/suggestion/SuggestionEngineImplTest.java
  src/test/java/com/notably/logic/suggestion/SuggestionTestUtil.java
Labels: priority.High, type.Enhancement

#429 Add shorthands in SuggestionCommandParser and SuggestionEngineImpl
  src/main/java/com/notably/logic/parser/suggestion/DeleteSuggestionCommandParser.java
  src/main/java/com/notably/logic/parser/suggestion/EditSuggestionCommandParser.java
  src/main/java/com/notably/logic/parser/suggestion/HelpSuggestionCommandParser.java
  src/main/java/com/notably/logic/parser/suggestion/NewSuggestionCommandParser.java
  src/main/java/com/notably/logic/parser/suggestion/OpenSuggestionCommandParser.java
  src/main/java/com/notably/logic/parser/suggestion/SearchSuggestionCommandParser.java
  src/main/java/com/notably/logic/suggestion/SuggestionEngineImpl.java
Labels: priority.High, type.Enhancement

#437 Implement comparable RelativePath and AbsolutePath
  src/main/java/com/notably/commons/path/AbsolutePath.java
  src/main/java/com/notably/commons/path/PathUtil.java
  src/main/java/com/notably/commons/path/RelativePath.java
  src/test/java/com/notably/commons/path/AbsolutePathTest.java
  src/test/java/com/notably/commons/path/RelativePathTest.java
Labels: priority.High, type.Enhancement

#441 Prevent user from editing Root Block
  src/main/java/com/notably/logic/commands/EditCommand.java
Labels: severity.Medium, type.Bug

#442 Fix path comparable bug
  src/main/java/com/notably/commons/path/AbsolutePath.java
  src/main/java/com/notably/commons/path/RelativePath.java
  src/test/java/com/notably/commons/path/AbsolutePathTest.java
  src/test/java/com/notably/commons/path/RelativePathTest.java
Labels: severity.High, type.Bug

#434 Update sug generation to take in a list of correction items
  src/main/java/com/notably/logic/commands/suggestion/DeleteSuggestionCommand.java
  src/main/java/com/notably/logic/commands/suggestion/OpenSuggestionCommand.java
  src/main/java/com/notably/logic/parser/suggestion/DeleteSuggestionCommandParser.java
  src/main/java/com/notably/logic/parser/suggestion/OpenSuggestionCommandParser.java
  src/test/java/com/notably/logic/commands/suggestion/DeleteSuggestionCommandTest.java
  src/test/java/com/notably/logic/commands/suggestion/OpenSuggestionCommandTest.java
  src/test/java/com/notably/logic/parser/suggestion/DeleteSuggestionCommandParserTest.java
  src/test/java/com/notably/logic/parser/suggestion/OpenSuggestionCommandParserTest.java
  src/test/java/com/notably/logic/suggestion/SuggestionEngineImplTest.java
Labels: priority.High, type.Enhancement

#407 Update currentlyOpenBlock on block delete
  src/main/java/com/notably/model/block/BlockModelImpl.java
  src/main/java/com/notably/model/block/BlockTreeItem.java
  src/main/java/com/notably/model/block/BlockTreeItemImpl.java
  src/test/java/com/notably/model/block/BlockModelTest.java
Labels: priority.High, severity.High, type.Bug

#432 Revamp NewCommand and improve ErrorMessages
  src/main/java/com/notably/logic/LogicManager.java
  src/main/java/com/notably/logic/parser/DeleteCommandParser.java
  src/main/java/com/notably/logic/parser/NewCommandParser.java
  src/main/java/com/notably/logic/parser/NotablyParser.java
  src/main/java/com/notably/logic/parser/OpenCommandParser.java
  src/main/java/com/notably/logic/parser/ParserUtil.java
  src/main/java/com/notably/logic/parser/exceptions/ParseException.java
  src/test/java/com/notably/logic/LogicManagerTest.java
  src/test/java/com/notably/logic/parser/NotablyParserTest.java
Labels: priority.High, type.Enhancement

#291 Improve test coverage of Parser and Command
  src/test/java/com/notably/logic/commands/DeleteCommandTest.java
  src/test/java/com/notably/logic/commands/EditCommandTest.java
  src/test/java/com/notably/logic/commands/HelpCommandTest.java
  src/test/java/com/notably/logic/commands/NewCommandTest.java
  src/test/java/com/notably/logic/commands/OpenCommandTest.java
  src/test/java/com/notably/logic/parser/DeleteCommandParserTest.java
  src/test/java/com/notably/logic/parser/NewCommandParserTest.java
  src/test/java/com/notably/logic/parser/NotablyParserTest.java
  src/test/java/com/notably/logic/parser/OpenCommandParserTest.java
Labels: priority.High, status.Ongoing, type.Enhancement

#435 Disallow RelativePath in Title
  src/main/java/com/notably/logic/parser/suggestion/NewSuggestionCommandParser.java
  src/main/java/com/notably/model/block/Title.java
  src/test/java/com/notably/logic/parser/suggestion/NewSuggestionCommandParserTest.java
  src/test/java/com/notably/model/block/TitleTest.java
Labels: severity.Medium, status.Ongoing, type.Bug

#445 Enable traversal and selection of Suggestions via Keyboard.
  src/main/java/com/notably/view/CommandBox.java
  src/main/java/com/notably/view/SuggestionsWindowView.java
Labels: priority.High, type.Enhancement

#449 CorrectionEngine improvements
  src/main/java/com/notably/logic/commands/DeleteCommand.java
  src/main/java/com/notably/logic/commands/EditCommand.java
  src/main/java/com/notably/logic/commands/HelpCommand.java
  src/main/java/com/notably/logic/commands/NewCommand.java
  src/main/java/com/notably/logic/commands/OpenCommand.java
  src/main/java/com/notably/logic/correction/AbsolutePathCorrectionEngine.java
  src/main/java/com/notably/logic/correction/CorrectionEngineParameters.java
  src/main/java/com/notably/logic/correction/CorrectionEngineUtil.java
  src/main/java/com/notably/logic/correction/StringCorrectionEngine.java
  src/main/java/com/notably/logic/parser/NotablyParser.java
  src/main/java/com/notably/logic/parser/suggestion/DeleteSuggestionCommandParser.java
  src/main/java/com/notably/logic/parser/suggestion/EditSuggestionCommandParser.java
  src/main/java/com/notably/logic/parser/suggestion/HelpSuggestionCommandParser.java
  src/main/java/com/notably/logic/parser/suggestion/NewSuggestionCommandParser.java
  src/main/java/com/notably/logic/parser/suggestion/OpenSuggestionCommandParser.java
  src/main/java/com/notably/logic/parser/suggestion/SearchSuggestionCommandParser.java
  src/main/java/com/notably/logic/suggestion/SuggestionEngineImpl.java
  src/test/java/com/notably/logic/correction/AbsolutePathCorrectionEngineTest.java
  src/test/java/com/notably/logic/correction/StringCorrectionEngineTest.java
  src/test/java/com/notably/logic/parser/DeleteCommandParserTest.java
  src/test/java/com/notably/logic/parser/OpenCommandParserTest.java
  src/test/java/com/notably/logic/parser/suggestion/DeleteSuggestionCommandParserTest.java
  src/test/java/com/notably/logic/parser/suggestion/OpenSuggestionCommandParserTest.java
  src/test/java/com/notably/logic/suggestion/SuggestionEngineImplTest.java
Labels: priority.High, type.Enhancement

#451 Sort suggestion list based on the frequency for search command
  src/main/java/com/notably/logic/commands/suggestion/SearchSuggestionCommand.java
  src/test/java/com/notably/logic/commands/suggestion/SearchSuggestionCommandTest.java
  src/test/java/com/notably/logic/parser/suggestion/SearchSuggestionCommandParserTest.java
  src/test/java/com/notably/logic/suggestion/SuggestionEngineImplTest.java
  src/test/java/com/notably/logic/suggestion/SuggestionTestUtil.java
Labels: priority.High, type.Enhancement

#443 Feature: UI Overhaul
  docs/DeveloperGuide.adoc
  src/main/java/com/notably/model/viewstate/ViewStateModelImpl.java
  src/main/java/com/notably/view/MainWindow.java
  src/main/java/com/notably/view/SideBarTreeView.java
  src/main/java/com/notably/view/StatusBarFooter.java
  src/main/java/com/notably/view/SuggestionsWindowView.java
  src/main/java/com/notably/view/blockcontent/BlockContentDisplayView.java
  src/main/resources/fonts/Roboto-Bold.ttf
  src/main/resources/fonts/Roboto-BoldItalic.ttf
  src/main/resources/fonts/Roboto-Italic.ttf
  src/main/resources/fonts/Roboto-Medium.ttf
  src/main/resources/fonts/Roboto-MediumItalic.ttf
  src/main/resources/fonts/Roboto-Regular.ttf
  src/main/resources/images/cheveron-collapse.png
  src/main/resources/images/cheveron-expand.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/NotablyTheme.css
  src/main/resources/view/StatusBarFooter.fxml
  src/main/resources/view/SuggestionsWindowView.fxml
  src/main/resources/view/blockcontent/BlockContentDisplay.css
  src/main/resources/view/blockcontent/BlockContentDisplayView.fxml
  src/test/java/com/notably/model/viewstate/ViewStateModelTest.java
Labels: priority.High, status.Ongoing

#452 Improve Compiler's testing
  src/test/data/CompilerTest/Compiled.html
  src/test/data/CompilerTest/Markdown.md
Labels: priority.High, type.Task

#453 Add logging to StringCorrectionEngine and AbsolutePathCorrectionEngine
  src/main/java/com/notably/logic/correction/AbsolutePathCorrectionEngine.java
  src/main/java/com/notably/logic/correction/CorrectionEngine.java
  src/main/java/com/notably/logic/correction/StringCorrectionEngine.java
  src/main/java/com/notably/logic/correction/distance/EditDistanceCalculator.java
  src/main/java/com/notably/logic/correction/distance/LevenshteinDistanceCalculator.java
Labels: priority.High, type.Enhancement

#447 Add Log and AssertNull to Command and Parser
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/com/notably/commons/path/AbsolutePath.java
  src/main/java/com/notably/commons/path/RelativePath.java
  src/main/java/com/notably/logic/LogicManager.java
  src/main/java/com/notably/logic/commands/DeleteCommand.java
  src/main/java/com/notably/logic/commands/EditCommand.java
  src/main/java/com/notably/logic/commands/ExitCommand.java
  src/main/java/com/notably/logic/commands/HelpCommand.java
  src/main/java/com/notably/logic/commands/NewCommand.java
  src/main/java/com/notably/logic/commands/OpenCommand.java
  src/main/java/com/notably/logic/parser/DeleteCommandParser.java
  src/main/java/com/notably/logic/parser/NewCommandParser.java
  src/main/java/com/notably/logic/parser/NotablyParser.java
  src/main/java/com/notably/logic/parser/OpenCommandParser.java
  src/main/java/com/notably/logic/parser/ParserUtil.java
Labels: priority.High, type.Enhancement

#463 Update log file name
  src/main/java/com/notably/commons/LogsCenter.java
Labels: priority.High, type.Task

#465 Add logging to Compiler
  src/main/java/com/notably/commons/compiler/Compiler.java
Labels: priority.High, type.Task

#457 Remove SugEngine and rename SugEngineImpl to SugEngine
  src/main/java/com/notably/logic/LogicManager.java
  src/main/java/com/notably/logic/suggestion/SuggestionEngine.java
  src/main/java/com/notably/logic/suggestion/SuggestionEngineImpl.java
  src/test/java/com/notably/logic/suggestion/SuggestionEngineTest.java
Labels: priority.High, type.Enhancement

#467 Improve ParserUtil#createAbsolutePath's error handling
  src/main/java/com/notably/logic/parser/ParserUtil.java
Labels: severity.Low, type.Bug

#461 Update UG and README
  README.adoc
  docs/UserGuide.adoc
Labels: priority.High, type.Enhancement

#455 Update traverse tree method in SearchSugCmd
  src/main/java/com/notably/logic/commands/suggestion/SearchSuggestionCommand.java
Labels: priority.High, type.Enhancement

#448 Add Title and Body Displays to Block Content View
  src/main/java/com/notably/view/CommandBox.java
  src/main/java/com/notably/view/MainWindow.java
  src/main/java/com/notably/view/blockcontent/BlockContent.java
  src/main/java/com/notably/view/blockcontent/BlockContentDisplayView.java
  src/main/java/com/notably/view/blockcontent/BlockContentEditView.java
  src/main/java/com/notably/view/sidebar/SideBarTreeView.java
  src/main/java/com/notably/view/sidebar/SideBarTreeViewCell.java
  src/main/java/com/notably/view/sidebar/TreeCellEventDispatcher.java
  src/main/java/com/notably/view/suggestion/SuggestionsListCellData.java
  src/main/java/com/notably/view/suggestion/SuggestionsListViewCell.java
  src/main/java/com/notably/view/suggestion/SuggestionsWindowView.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/NotablyTheme.css
  src/main/resources/view/blockcontent/BlockContentDisplay.css
  src/main/resources/view/blockcontent/BlockContentDisplayView.fxml
  src/main/resources/view/blockcontent/BlockContentEditView.fxml
  src/main/resources/view/suggestion/SuggestionsListViewCell.fxml
  src/main/resources/view/suggestion/SuggestionsWindowView.fxml
Labels: priority.High, type.Enhancement

#474 Fixes race condition bug during delete
  src/main/java/com/notably/model/block/BlockModelImpl.java
Labels: severity.High, status.Ongoing, type.Bug

#459 Clean up tests and Javadoc for Block, UserPrefs and Storage
  src/main/java/com/notably/model/Model.java
  src/main/java/com/notably/model/ModelManager.java
  src/main/java/com/notably/model/block/Block.java
  src/main/java/com/notably/model/block/BlockImpl.java
  src/main/java/com/notably/model/block/BlockModel.java
  src/main/java/com/notably/model/block/BlockModelImpl.java
  src/main/java/com/notably/model/block/BlockTree.java
  src/main/java/com/notably/model/block/BlockTreeImpl.java
  src/main/java/com/notably/model/block/BlockTreeItem.java
  src/main/java/com/notably/model/block/BlockTreeItemImpl.java
  src/main/java/com/notably/model/block/Body.java
  src/main/java/com/notably/model/block/Title.java
  src/main/java/com/notably/model/block/exceptions/CannotModifyRootException.java
  src/main/java/com/notably/model/block/exceptions/DuplicateBlockException.java
  src/main/java/com/notably/model/block/exceptions/NoSuchBlockException.java
  src/main/java/com/notably/model/userpref/ReadOnlyUserPrefModel.java
  src/main/java/com/notably/model/userpref/UserPrefModel.java
  src/main/java/com/notably/model/userpref/UserPrefModelImpl.java
  src/main/java/com/notably/storage/StorageManager.java
  src/test/java/com/notably/model/block/BlockModelTest.java
  src/test/java/com/notably/model/block/BlockTreeTest.java
  src/test/java/com/notably/storage/JsonBlockStorageTest.java
  src/test/java/com/notably/testutil/EditPersonDescriptorBuilder.java
Labels: priority.High, status.Ongoing, type.Task

#470 Clear input property in runnable action of sug item for search cmd
  src/main/java/com/notably/logic/suggestion/generator/SearchSuggestionGenerator.java
  src/main/java/com/notably/model/ModelManager.java
  src/main/java/com/notably/model/viewstate/CommandInputModel.java
  src/main/java/com/notably/model/viewstate/ViewStateModelImpl.java
  src/test/java/com/notably/logic/suggestion/SuggestionEngineTest.java
  src/test/java/com/notably/logic/suggestion/SuggestionTestUtil.java
  src/test/java/com/notably/logic/suggestion/generator/SearchSuggestionGeneratorTest.java
  src/test/java/com/notably/logic/suggestion/handler/SearchSuggestionArgHandlerTest.java
Labels: priority.High, type.Enhancement

#468 Parse Search when the command is incomplete
  src/main/java/com/notably/logic/parser/NotablyParser.java
  src/main/java/com/notably/logic/parser/SearchCommandParser.java
  src/test/java/com/notably/logic/parser/SearchCommandParserTest.java
Labels: severity.High, type.Bug

#476 Disable root
  src/main/java/com/notably/logic/parser/OpenCommandParser.java
  src/test/java/com/notably/logic/parser/OpenCommandParserTest.java
Labels: priority.High, type.Enhancement

#479 Add logging to suggestions
  src/main/java/com/notably/logic/suggestion/generator/DeleteSuggestionGenerator.java
  src/main/java/com/notably/logic/suggestion/generator/OpenSuggestionGenerator.java
  src/main/java/com/notably/logic/suggestion/generator/SearchSuggestionGenerator.java
  src/main/java/com/notably/logic/suggestion/handler/DeleteSuggestionArgHandler.java
  src/main/java/com/notably/logic/suggestion/handler/EditSuggestionHandler.java
  src/main/java/com/notably/logic/suggestion/handler/ExitSuggestionHandler.java
  src/main/java/com/notably/logic/suggestion/handler/HelpSuggestionHandler.java
  src/main/java/com/notably/logic/suggestion/handler/NewSuggestionArgHandler.java
  src/main/java/com/notably/logic/suggestion/handler/OpenSuggestionArgHandler.java
  src/main/java/com/notably/logic/suggestion/handler/SearchSuggestionArgHandler.java
Labels: priority.High, type.Enhancement

#488 Add newline in javadoc
  src/main/java/com/notably/model/suggestion/SuggestionModel.java
Labels: priority.High, type.Enhancement

#489 Update UI Mockups in UG
  docs/UserGuide.adoc
  docs/images/Legends.png
  docs/images/Ui.png
  docs/images/demo/Correction.png
  docs/images/demo/Delete1.png
  docs/images/demo/Edit.png
  docs/images/demo/Edit1.png
  docs/images/demo/Edit2.png
  docs/images/demo/Exit.png
  docs/images/demo/Help.png
  docs/images/demo/New1.png
  docs/images/demo/New2.png
  docs/images/demo/New3.png
  docs/images/demo/Open.png
  docs/images/demo/Search.png
  docs/images/demo/Suggestions.png
Labels: priority.High, type.Task

#495 Fix search sorting bug
  src/main/java/com/notably/logic/suggestion/generator/SearchSuggestionGenerator.java
  src/test/java/com/notably/logic/suggestion/SuggestionTestUtil.java
  src/test/java/com/notably/logic/suggestion/generator/SearchSuggestionGeneratorTest.java
Labels: severity.High, type.Bug

#496 Update markdown section in UG
  docs/UserGuide.adoc
Labels: priority.High, type.Task

#490 Add Firzan's PPP and other relevant changes
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/firzanarmani.adoc
Labels: priority.High, status.Ongoing, type.Task

#482 Updated UG
  docs/UserGuide.adoc
  docs/images/UGPathDiagram.png
Labels: priority.Medium, type.Task

#484 Update DG for suggestions
  docs/DeveloperGuide.adoc
  docs/DeveloperGuide.pdf
  docs/diagrams/SuggestionClassDiagram.puml
  docs/diagrams/SuggestionEngineClassDiagram.puml
  docs/diagrams/SuggestionSequenceDiagram.puml
  docs/images/SuggestionClassDiagram.png
  docs/images/SuggestionSequenceDiagram.png
Labels: priority.High, status.Ongoing, type.Enhancement

#493 Update ug
  docs/UserGuide.adoc
  docs/images/demo/ResponseText1.png
  docs/images/demo/ResponseText2.png
  docs/images/demo/Search.png
  docs/images/demo/Search1.png
  docs/images/demo/Suggestions.png
  docs/images/demo/Suggestions2.png
  docs/images/demo/Suggestions3.png
  docs/images/demo/Suggestions4.png
Labels: priority.High, status.Ongoing, type.Enhancement

#491 Update correction section of the UG
  docs/UserGuide.adoc
Labels: priority.High, type.Task

#498 Add markdown usage example
  docs/UserGuide.adoc
Labels: priority.High, type.Task

#499 Update Architecture section of DG
  docs/DeveloperGuide.adoc
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
Labels: priority.High, type.Task

#504 Markdown DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/CompilerClassDiagram.puml
  docs/diagrams/CompilerSequenceDiagram.puml
  docs/diagrams/StringCorrectionEngineSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/CompilerClassDiagram.png
  docs/images/CompilerSequenceDiagram.png
  docs/images/StringCorrectionEngineSequenceDiagram.png
Labels: priority.High, type.Task

#501 Update UG - Firzan's parts
  docs/UserGuide.adoc
  docs/images/demo/Delete3.png
  docs/images/demo/New1.png
  docs/images/demo/New2.png
  docs/images/demo/New3.png
  docs/images/demo/PathDuplicates1.png
  docs/images/demo/PathDuplicates2.png
  docs/images/demo/PathDuplicates3.png
  docs/images/demo/Sidebar.png
  docs/images/demo/Sidebar2.png
Labels: priority.High, status.Ongoing, type.Task

#486 Johanna's PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/johannagwan.adoc
Labels: priority.High, status.Ongoing

#507 Kevin's PPP
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/kevinputera.adoc
Labels: priority.High, type.Task

#506 DG Update path and Parser diagram
  docs/DeveloperGuide.adoc
  docs/diagrams/LogicClassDiagram.puml
  docs/images/LogicClassDiagram.png
Labels: priority.High

#515 DG manual testing
  docs/DeveloperGuide.adoc
Labels: priority.High

#514 Enable Root Open
  src/main/java/com/notably/logic/parser/OpenCommandParser.java
Labels: priority.High, type.Enhancement

#497 Jia Zheng's PPP
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/ljiazh3ng.adoc
  src/main/java/com/notably/commons/parser/CliSyntax.java
Labels: priority.High, status.Ongoing
