Repository AY1920S2-CS2103T-W17-2/main, pull requests merged in 2020-03, with the labels that each got.

#36 Rename ...Ui to ...View
  README.adoc
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/UsingPlantUml.adoc
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/tutorials/AddRemark.adoc
  docs/tutorials/TracingCode.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/Ui.java
  src/main/java/seedu/address/view/CommandBox.java
  src/main/java/seedu/address/view/HelpWindow.java
  src/main/java/seedu/address/view/MainWindow.java
  src/main/java/seedu/address/view/PersonCard.java
  src/main/java/seedu/address/view/PersonListPanel.java
  src/main/java/seedu/address/view/ResultDisplay.java
  src/main/java/seedu/address/view/StatusBarFooter.java
  src/main/java/seedu/address/view/View.java
  src/main/java/seedu/address/view/ViewManager.java
  src/main/java/seedu/address/view/ViewPart.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/address/view/TestFxmlObject.java
  src/test/java/seedu/address/view/ViewPartTest.java
  src/test/resources/view/ViewPartTest/invalidFile.fxml
  src/test/resources/view/ViewPartTest/validFile.fxml
  src/test/resources/view/ViewPartTest/validFileWithFxRoot.fxml
Labels: type.Task

#43 Added target user profile, value proposition, and user stories
  docs/DeveloperGuide.adoc
Labels: type.Task

#46 Update architecture diagram, use cases, NFRs, and glossary to developer guide
  docs/DeveloperGuide.adoc
  docs/images/ArchitectureDiagram.png
Labels: type.Task

#50 Rename website header and Remove LO from readme
  README.adoc
  docs/LearningOutcomes.adoc
Labels: type.Task

#51 Update README
  README.adoc
Labels: type.Task

#53 Update User Guide
  docs/UserGuide.adoc
Labels: type.Bug

#49 Update 'About Us' and 'Contact Us' pages
  docs/AboutUs.adoc
  docs/ContactUs.adoc
  docs/images/damithc.jpg
  docs/images/firzanarmani.png
  docs/images/hemanshugandhi.png
  docs/images/johannagwan.png
  docs/images/kevinputera.png
  docs/images/lejolly.jpg
  docs/images/ljiazh3ng.png
  docs/images/m133225.jpg
  docs/images/yijinl.jpg
  docs/images/yl_coder.jpg
  docs/team/portfolio_template.adoc
Labels: type.Task

#54 Rename Ui->View Renaming Bug
  docs/images/View.png
Labels: type.Bug

#61 [BUGFIX] Ui.png missing (grading failed)
  docs/images/Ui.png
Labels: type.Bug

#63 Update DG title to be "Notably - Developer Guide"
  docs/DeveloperGuide.adoc
Labels: type.Task

#64 View & Logic: remove results display
  src/main/java/seedu/address/view/MainWindow.java
  src/main/java/seedu/address/view/ResultDisplay.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Task

#48 Remove Person model and its dependent model classes
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/view/PersonCard.java
  src/main/java/seedu/address/view/PersonListPanel.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#44 Delete Messages class
  .vs/ProjectSettings.json
  .vs/VSWorkspaceState.json
  src/main/java/com/notably/commons/core/Messages.java
  src/main/java/com/notably/logic/commands/DeleteCommand.java
  src/main/java/com/notably/logic/commands/EditCommand.java
  src/main/java/com/notably/logic/commands/FindCommand.java
  src/main/java/com/notably/logic/parser/AddCommandParser.java
  src/main/java/com/notably/logic/parser/AddressBookParser.java
  src/main/java/com/notably/logic/parser/DeleteCommandParser.java
  src/main/java/com/notably/logic/parser/EditCommandParser.java
  src/main/java/com/notably/logic/parser/FindCommandParser.java
  src/test/java/com/notably/logic/LogicManagerTest.java
  src/test/java/com/notably/logic/commands/CommandTestUtil.java
  src/test/java/com/notably/logic/commands/DeleteCommandTest.java
  src/test/java/com/notably/logic/commands/EditCommandTest.java
  src/test/java/com/notably/logic/commands/FindCommandTest.java
  src/test/java/com/notably/logic/parser/AddCommandParserTest.java
  src/test/java/com/notably/logic/parser/AddressBookParserTest.java
  src/test/java/com/notably/logic/parser/DeleteCommandParserTest.java
  src/test/java/com/notably/logic/parser/EditCommandParserTest.java
  src/test/java/com/notably/logic/parser/FindCommandParserTest.java
  src/test/java/com/notably/model/AddressBookTest.java
  src/test/java/com/notably/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/com/notably/model/person/PersonTest.java
  src/test/java/com/notably/model/person/UniquePersonListTest.java
  src/test/java/com/notably/storage/JsonAdaptedPersonTest.java
  src/test/java/com/notably/testutil/PersonBuilder.java
  src/test/java/com/notably/testutil/PersonUtil.java
  src/test/java/com/notably/testutil/TypicalPersons.java
Labels: status.Ongoing, type.Task

#69 Implement CorrectionEngine interfaces
  src/main/java/com/notably/logic/correction/CorrectionEngine.java
  src/main/java/com/notably/logic/correction/CorrectionResult.java
  src/main/java/com/notably/logic/correction/CorrectionStatus.java
Labels: priority.High, type.Task

#71 Remove unused CI config
  appveyor.yml
  build.gradle
Labels: type.Task

#76 Remove ListCommand and its relevant usages/ references
  src/main/java/com/notably/logic/commands/ListCommand.java
  src/main/java/com/notably/logic/parser/AddressBookParser.java
  src/test/java/com/notably/logic/LogicManagerTest.java
  src/test/java/com/notably/logic/commands/ListCommandTest.java
  src/test/java/com/notably/logic/parser/AddressBookParserTest.java
Labels: type.Task

#75 Remove FindCommand and its relevant usages/ references
  src/main/java/com/notably/logic/commands/FindCommand.java
  src/main/java/com/notably/logic/parser/AddressBookParser.java
  src/main/java/com/notably/logic/parser/FindCommandParser.java
  src/test/java/com/notably/logic/commands/FindCommandTest.java
  src/test/java/com/notably/logic/parser/AddressBookParserTest.java
  src/test/java/com/notably/logic/parser/FindCommandParserTest.java
Labels: type.Task

#78 Remove coverage and coveralls scripts from travis config
  .travis.yml
Labels: severity.High, type.Bug

#79 Update gh pages template
  build.gradle
  docs/templates/_header.html.slim
Labels: status.Ongoing, type.Task

#73 Remove Messages class and its usages
  src/main/java/com/notably/commons/core/Messages.java
  src/main/java/com/notably/logic/commands/DeleteCommand.java
  src/main/java/com/notably/logic/commands/EditCommand.java
  src/main/java/com/notably/logic/parser/AddCommandParser.java
  src/main/java/com/notably/logic/parser/AddressBookParser.java
  src/main/java/com/notably/logic/parser/DeleteCommandParser.java
  src/main/java/com/notably/logic/parser/EditCommandParser.java
  src/test/java/com/notably/logic/parser/AddressBookParserTest.java
  src/test/java/com/notably/logic/parser/DeleteCommandParserTest.java
Labels: type.Task

#80 Remove CommandResult
  src/main/java/com/notably/logic/Logic.java
  src/main/java/com/notably/logic/LogicManager.java
  src/main/java/com/notably/logic/commands/AddCommand.java
  src/main/java/com/notably/logic/commands/ClearCommand.java
  src/main/java/com/notably/logic/commands/Command.java
  src/main/java/com/notably/logic/commands/CommandResult.java
  src/main/java/com/notably/logic/commands/DeleteCommand.java
  src/main/java/com/notably/logic/commands/EditCommand.java
  src/main/java/com/notably/logic/commands/ExitCommand.java
  src/main/java/com/notably/logic/commands/HelpCommand.java
  src/main/java/com/notably/view/CommandBox.java
  src/main/java/com/notably/view/MainWindow.java
  src/test/java/com/notably/logic/commands/CommandResultTest.java
  src/test/java/com/notably/logic/commands/CommandTestUtil.java
Labels: status.Ongoing, type.Task

#83 Path
  src/main/java/com/notably/model/block/Path.java
  src/main/java/com/notably/model/block/exceptions/DuplicateBlockException.java
  src/main/java/com/notably/model/person/exceptions/DuplicatePersonException.java
  src/main/java/com/notably/model/person/exceptions/PersonNotFoundException.java
Labels: priority.High, type.Task

#93 Implement SuggestionEngine interfaces
  src/main/java/com/notably/logic/suggestion/SuggestionCommand.java
  src/main/java/com/notably/logic/suggestion/SuggestionEngine.java
  src/main/java/com/notably/model/suggestion/SuggestionItem.java
  src/main/java/com/notably/model/suggestion/SuggestionModel.java
Labels: priority.High, status.Ongoing, type.Enhancement

#87 Implement EditDistanceCalculator interface
  src/main/java/com/notably/logic/correction/distance/EditDistanceCalculator.java
Labels: priority.High, type.Enhancement

#94 Implement LevenshteinDistanceCalculator
  src/main/java/com/notably/logic/correction/distance/LevenshteinDistanceCalculator.java
  src/test/java/com/notably/logic/correction/distance/LevenshteinDistanceCalculatorTest.java
Labels: priority.High, type.Enhancement

#102 Implement skeletons for AbsolutePath and RelativePath
  src/main/java/com/notably/commons/core/path/AbsolutePath.java
  src/main/java/com/notably/commons/core/path/Path.java
  src/main/java/com/notably/commons/core/path/RelativePath.java
  src/main/java/com/notably/commons/core/path/exceptions/InvalidPathException.java
  src/main/java/com/notably/model/block/Path.java
Labels: priority.High, type.Task

#101 Implement Block interface
  src/main/java/com/notably/model/block/Block.java
  src/main/java/com/notably/model/block/Body.java
  src/main/java/com/notably/model/block/Title.java
Labels: status.Ongoing, type.Task

#105 Revamp CorrectionEngine + CorrectionResult interfaces
  src/main/java/com/notably/logic/correction/CorrectionEngine.java
  src/main/java/com/notably/logic/correction/CorrectionResult.java
Labels: priority.High, type.Enhancement

#106 Initialise CommandInputModel [Model]
  src/main/java/com/notably/model/commandinput/CommandInputModel.java
  src/main/java/com/notably/model/commandinput/CommandInputModelImpl.java
Labels: type.Enhancement

#110 Implement StringCorrectionEngine
  src/main/java/com/notably/logic/correction/CorrectionEngine.java
  src/main/java/com/notably/logic/correction/CorrectionResult.java
  src/main/java/com/notably/logic/correction/StringCorrectionEngine.java
  src/main/java/com/notably/logic/correction/distance/LevenshteinDistanceCalculator.java
  src/test/java/com/notably/logic/correction/StringCorrectionEngineTest.java
Labels: priority.High, type.Enhancement

#108 Add BlockImpl concrete class
  src/main/java/com/notably/model/block/BlockImpl.java
  src/main/java/com/notably/model/block/exceptions/NoSuchBlockException.java
Labels: priority.High, status.Ongoing, type.Task

#119 Add SuggestionItemImpl class
  src/main/java/com/notably/model/suggestion/SuggestionItem.java
  src/main/java/com/notably/model/suggestion/SuggestionItemImpl.java
Labels: priority.High, status.Ongoing, type.Enhancement

#116 Absolute and Relative paths
  src/main/java/com/notably/commons/core/path/AbsolutePath.java
  src/main/java/com/notably/commons/core/path/RelativePath.java
  src/main/java/com/notably/commons/core/path/exceptions/InvalidPathException.java
  src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java
  src/test/java/com/notably/commons/core/Path/RelativePathTest.java
Labels: type.Task

#132 Make Model extend CommandInputModel
  src/main/java/com/notably/model/Model.java
  src/main/java/com/notably/model/ModelManager.java
Labels: priority.High, status.Ongoing, type.Enhancement

#123 Add suggestion model implementation
  src/main/java/com/notably/model/suggestion/SuggestionModel.java
  src/main/java/com/notably/model/suggestion/SuggestionModelImpl.java
Labels: priority.High, status.Ongoing, type.Enhancement

#124 Make Model extend SuggestionModel
  src/main/java/com/notably/model/Model.java
  src/main/java/com/notably/model/ModelManager.java
Labels: priority.High, status.Ongoing, type.Enhancement

#138 Fix correction classes' visibility bugs
  src/main/java/com/notably/logic/correction/CorrectionEngine.java
  src/main/java/com/notably/logic/correction/CorrectionResult.java
  src/main/java/com/notably/logic/correction/CorrectionStatus.java
Labels: priority.High, type.Bug

#127 Add Notably UI Skeleton [View]
  copyright.txt
  src/main/java/com/notably/MainApp.java
  src/main/java/com/notably/view/BlockContentEditView.java
  src/main/java/com/notably/view/MainWindow.java
  src/main/java/com/notably/view/SideBarTreeView.java
  src/main/java/com/notably/view/StatusBarFooter.java
  src/main/java/com/notably/view/ViewManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/notably_logo_48.png
  src/main/resources/view/BlockContentEditView.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/SideBarTreeView.fxml
  src/test/java/com/notably/commons/util/AppUtilTest.java
Labels: priority.High, status.Ongoing

#141 Modify Body validity condition and add tests for Title and Body
  src/main/java/com/notably/model/block/Body.java
  src/main/java/com/notably/model/block/Title.java
  src/test/java/com/notably/model/block/BodyTest.java
  src/test/java/com/notably/model/block/TitleTest.java
Labels: priority.High, severity.High, type.Bug

#143 Change the definition for root in Paths
  src/main/java/com/notably/commons/core/path/AbsolutePath.java
  src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java
Labels: priority.Low, type.Task

#148 Add BlockTree and BlockTreeItem interfaces
  src/main/java/com/notably/model/block/Block.java
  src/main/java/com/notably/model/block/BlockImpl.java
  src/main/java/com/notably/model/block/BlockTree.java
  src/main/java/com/notably/model/block/BlockTreeItem.java
Labels: priority.High, status.Ongoing, type.Task

#146 Implement getStringRepresentation method in Path classes
  src/main/java/com/notably/commons/core/path/AbsolutePath.java
  src/main/java/com/notably/commons/core/path/Path.java
  src/main/java/com/notably/commons/core/path/RelativePath.java
Labels: priority.High, type.Task

#150 Add BlockModel interface
  src/main/java/com/notably/model/BlockModel.java
Labels: priority.High, status.Ongoing, type.Task

#154 Update Model to extend BlockModel and minor changes to BlockModel
  src/main/java/com/notably/model/BlockModel.java
  src/main/java/com/notably/model/Model.java
  src/main/java/com/notably/model/ModelManager.java
Labels: priority.High, status.Ongoing, type.Task

#157 Implement ModelStubBase
  src/test/java/com/notably/testutil/AddressBookBuilder.java
  src/test/java/com/notably/testutil/EditPersonDescriptorBuilder.java
  src/test/java/com/notably/testutil/ModelStubBase.java
Labels: priority.High, type.Task

#151 Add BlockTree and BlockTreeItem implementations
  src/main/java/com/notably/model/block/BlockTree.java
  src/main/java/com/notably/model/block/BlockTreeImpl.java
  src/main/java/com/notably/model/block/BlockTreeItemImpl.java
  src/main/java/com/notably/model/block/exceptions/CannotModifyRootException.java
  src/test/java/com/notably/model/block/BlockTreeItemTest.java
  src/test/java/com/notably/model/block/BlockTreeTest.java
Labels: priority.High, status.Ongoing, type.Task

#152 Implement AbsolutePathCorrectionEngine
  src/main/java/com/notably/logic/correction/AbsolutePathCorrectionEngine.java
  src/test/java/com/notably/logic/correction/AbsolutePathCorrectionEngineTest.java
Labels: priority.High, type.Enhancement

#171 Make InvalidPathException a RuntimeException
  src/main/java/com/notably/commons/core/path/AbsolutePath.java
  src/main/java/com/notably/commons/core/path/RelativePath.java
  src/main/java/com/notably/commons/core/path/exceptions/InvalidPathException.java
  src/main/java/com/notably/logic/correction/AbsolutePathCorrectionEngine.java
  src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java
  src/test/java/com/notably/commons/core/Path/RelativePathTest.java
  src/test/java/com/notably/logic/correction/AbsolutePathCorrectionEngineTest.java
  src/test/java/com/notably/model/block/BlockTreeTest.java
Labels: priority.High, type.Task

#144 Create OpenSuggestionCommand and OpenSuggestionCommandTest
  src/main/java/com/notably/logic/suggestion/commands/OpenSuggestionCommand.java
  src/test/java/com/notably/logic/suggestion/commands/OpenSuggestionCommandTest.java
Labels: priority.High, status.Ongoing, type.Enhancement

#159 Create ViewStateModel to support help/exit commands [Model]
  src/main/java/com/notably/MainApp.java
  src/main/java/com/notably/model/Model.java
  src/main/java/com/notably/model/ModelManager.java
  src/main/java/com/notably/model/commandinput/CommandInputModelImpl.java
  src/main/java/com/notably/model/viewstate/CommandInputModel.java
  src/main/java/com/notably/model/viewstate/HelpFlagModel.java
  src/main/java/com/notably/model/viewstate/ViewStateModel.java
  src/main/java/com/notably/model/viewstate/ViewStateModelImpl.java
  src/test/java/com/notably/testutil/ModelStubBase.java
Labels: priority.High, type.Enhancement

#167 Add BlockModel implementations
  src/main/java/com/notably/commons/core/path/AbsolutePath.java
  src/main/java/com/notably/model/Model.java
  src/main/java/com/notably/model/ModelManager.java
  src/main/java/com/notably/model/block/Block.java
  src/main/java/com/notably/model/block/BlockImpl.java
  src/main/java/com/notably/model/block/BlockModel.java
  src/main/java/com/notably/model/block/BlockModelImpl.java
  src/main/java/com/notably/model/block/BlockTree.java
  src/main/java/com/notably/model/block/BlockTreeImpl.java
  src/main/java/com/notably/model/block/BlockTreeItem.java
  src/main/java/com/notably/model/block/BlockTreeItemImpl.java
  src/main/java/com/notably/model/block/exceptions/CannotModifyRootException.java
  src/test/java/com/notably/model/block/BlockModelTest.java
  src/test/java/com/notably/model/block/BlockTreeTest.java
Labels: priority.High, status.Ongoing, type.Task

#134 implement Notably parser and Command
  src/main/java/com/notably/logic/LogicManager.java
  src/main/java/com/notably/logic/commands/AddCommand.java
  src/main/java/com/notably/logic/commands/ClearCommand.java
  src/main/java/com/notably/logic/commands/DeleteCommand.java
  src/main/java/com/notably/logic/commands/EditCommand.java
  src/main/java/com/notably/logic/commands/ExitCommand.java
  src/main/java/com/notably/logic/commands/HelpCommand.java
  src/main/java/com/notably/logic/commands/NewCommand.java
  src/main/java/com/notably/logic/commands/OpenCommand.java
  src/main/java/com/notably/logic/parser/AddCommandParser.java
  src/main/java/com/notably/logic/parser/AddressBookParser.java
  src/main/java/com/notably/logic/parser/CliSyntax.java
  src/main/java/com/notably/logic/parser/CommandParser.java
  src/main/java/com/notably/logic/parser/DeleteCommandParser.java
  src/main/java/com/notably/logic/parser/EditCommandParser.java
  src/main/java/com/notably/logic/parser/NewCommandParser.java
  src/main/java/com/notably/logic/parser/NotablyParser.java
  src/main/java/com/notably/logic/parser/OpenCommandParser.java
  src/main/java/com/notably/logic/parser/Parser.java
  src/main/java/com/notably/model/BlockManager.java
  src/main/java/com/notably/model/BlockManagerStub.java
  src/test/java/com/notably/logic/commands/AddCommandIntegrationTest.java
  src/test/java/com/notably/logic/commands/CommandTestUtil.java
  src/test/java/com/notably/logic/commands/DeleteCommandTest.java
  src/test/java/com/notably/logic/commands/EditPersonDescriptorTest.java
  src/test/java/com/notably/logic/parser/AddressBookParserTest.java
  src/test/java/com/notably/logic/parser/ArgumentTokenizerTest.java
  src/test/java/com/notably/logic/parser/CommandParserTestUtil.java
  src/test/java/com/notably/logic/parser/DeleteCommandParserTest.java
  src/test/java/com/notably/logic/parser/EditCommandParserTest.java
  src/test/java/com/notably/logic/parser/NotablyParserTest.java
  src/test/java/com/notably/testutil/EditPersonDescriptorBuilder.java
Labels: priority.High

#173 Create SuggestionCommandParser interface
  src/main/java/com/notably/logic/suggestion/parser/SuggestionCommandParser.java
Labels: priority.High, status.Ongoing, type.Enhancement

#187 Rename getCurrentlyOpenPathProperty method to currentlyOpenPathProperty
  src/main/java/com/notably/model/ModelManager.java
  src/main/java/com/notably/model/block/BlockModel.java
  src/main/java/com/notably/model/block/BlockModelImpl.java
  src/test/java/com/notably/testutil/ModelStubBase.java
Labels: priority.High

#189 Add trailing whitespace to Title validation regex
  src/main/java/com/notably/model/block/Title.java
  src/test/java/com/notably/model/block/TitleTest.java
Labels: severity.High, type.Bug

#196 Clean up Model and ModelManager
  src/main/java/com/notably/MainApp.java
  src/main/java/com/notably/logic/Logic.java
  src/main/java/com/notably/logic/LogicManager.java
  src/main/java/com/notably/model/Model.java
  src/main/java/com/notably/model/ModelManager.java
  src/test/java/com/notably/testutil/ModelStubBase.java
  src/test/java/com/notably/testutil/TestUtil.java
Labels: priority.High, type.Task

#197 Remove ModelStubBase, test directly with Model
  src/test/java/com/notably/logic/correction/AbsolutePathCorrectionEngineTest.java
  src/test/java/com/notably/logic/suggestion/commands/OpenSuggestionCommandTest.java
  src/test/java/com/notably/testutil/ModelStubBase.java
Labels: priority.High, type.Task

#183 Redefine LogicManager's execute function
  src/main/java/com/notably/logic/Logic.java
  src/main/java/com/notably/logic/LogicManager.java
Labels: priority.High, type.Task

#175 Path accept spaces
  src/main/java/com/notably/commons/core/path/AbsolutePath.java
  src/main/java/com/notably/commons/core/path/RelativePath.java
  src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java
Labels: priority.High, type.Task

#179 Removed unused test case (Parser and Command)
  src/test/java/com/notably/logic/commands/AddCommandIntegrationTest.java
  src/test/java/com/notably/logic/commands/ClearCommandTest.java
  src/test/java/com/notably/logic/commands/CommandTestUtil.java
  src/test/java/com/notably/logic/commands/DeleteCommandTest.java
  src/test/java/com/notably/logic/commands/EditCommandTest.java
  src/test/java/com/notably/logic/commands/EditPersonDescriptorTest.java
  src/test/java/com/notably/logic/commands/ExitCommandTest.java
  src/test/java/com/notably/logic/commands/HelpCommandTest.java
  src/test/java/com/notably/logic/parser/AddressBookParserTest.java
  src/test/java/com/notably/logic/parser/ArgumentTokenizerTest.java
Labels: priority.Low, type.Task

#177 Add HelpCommand
  src/main/java/com/notably/logic/commands/HelpCommand.java
  src/main/java/com/notably/logic/parser/NotablyParser.java
  src/test/java/com/notably/logic/parser/NotablyParserTest.java
Labels: priority.Medium, type.Task

#201 Remove BlockManager and BlockManagerStub
  src/main/java/com/notably/model/BlockManager.java
  src/main/java/com/notably/model/BlockManagerStub.java
Labels: priority.High, type.Task

#192 Create NewSuggestionCommand and NewSuggestionCommandTest
  src/main/java/com/notably/logic/suggestion/commands/NewSuggestionCommand.java
  src/test/java/com/notably/logic/suggestion/commands/NewSuggestionCommandTest.java
Labels: priority.High, type.Enhancement

#200 Fix Title validation bugs
  src/main/java/com/notably/model/block/Title.java
  src/test/java/com/notably/model/block/TitleTest.java
Labels: priority.High, severity.High, type.Bug

#181 Move commonly used methods to ParserUtil
  src/main/java/com/notably/logic/commands/DeleteCommand.java
  src/main/java/com/notably/logic/commands/NewCommand.java
  src/main/java/com/notably/logic/commands/exceptions/CommandException.java
  src/main/java/com/notably/logic/parser/DeleteCommandParser.java
  src/main/java/com/notably/logic/parser/EditCommandParser.java
  src/main/java/com/notably/logic/parser/NewCommandParser.java
  src/main/java/com/notably/logic/parser/NotablyParser.java
  src/main/java/com/notably/logic/parser/OpenCommandParser.java
  src/main/java/com/notably/logic/parser/ParserUtil.java
Labels: priority.Low, type.Enhancement

#202 Make SimpleObjectProperty call in SuggestionModelImpl generic
  src/main/java/com/notably/model/suggestion/SuggestionModelImpl.java
Labels: priority.High, type.Task

#204 Create HelpSuggestionCommand and HelpSuggestionCommandTest
  src/main/java/com/notably/logic/suggestion/commands/HelpSuggestionCommand.java
  src/test/java/com/notably/logic/suggestion/commands/HelpSuggestionCommandTest.java
Labels: priority.High, type.Enhancement

#206 Remove path field and constructor from NewSuggestionCommand
  src/main/java/com/notably/logic/suggestion/commands/NewSuggestionCommand.java
  src/test/java/com/notably/logic/suggestion/commands/NewSuggestionCommandTest.java
Labels: priority.High, type.Enhancement

#208 Rename test method in OpenSuggestionCommandTest
  src/test/java/com/notably/logic/suggestion/commands/OpenSuggestionCommandTest.java
Labels: priority.High, type.Enhancement

#210 Link SideBarTreeView with BlockModel [View]
  src/main/java/com/notably/MainApp.java
  src/main/java/com/notably/view/MainWindow.java
  src/main/java/com/notably/view/SideBarTreeView.java
  src/main/java/com/notably/view/ViewManager.java
  src/main/resources/view/SideBarTreeView.fxml
Labels: priority.High, status.Ongoing

#216 Clean up misc documentations
  docs/AboutUs.adoc
  docs/ContactUs.adoc
  docs/DevOps.adoc
  docs/Documentation.adoc
  docs/SettingUp.adoc
  docs/Testing.adoc
  docs/UsingAppVeyor.adoc
  docs/UsingCheckstyle.adoc
  docs/UsingCoveralls.adoc
  docs/UsingGradle.adoc
  docs/UsingNetlify.adoc
  docs/UsingPlantUml.adoc
  docs/UsingTravis.adoc
Labels: priority.High, type.Task

#222 Update logic section of DG
  docs/DeveloperGuide.adoc
  docs/images/LogicArchitectureDiagram.png
Labels: priority.High, type.Task

#212 Create ExitSuggestionCommand and ExitSuggestionCommandTest
  src/main/java/com/notably/logic/suggestion/commands/ExitSuggestionCommand.java
  src/test/java/com/notably/logic/suggestion/commands/ExitSuggestionCommandTest.java
Labels: priority.High, type.Enhancement

#229 Set up Implementation section for DG
  docs/DeveloperGuide.adoc
Labels: priority.High, type.Task

#224 Revamp CorrectionEngine DG
  docs/DeveloperGuide.adoc
  docs/diagrams/CorrectionEngineClassDiagram.puml
  docs/diagrams/StringCorrectionEngineSequenceDiagram.puml
  docs/images/CorrectionEngineClassDiagram.png
  docs/images/StringCorrectionEngineSequenceDiagram.png
Labels: priority.High, type.Task

#223 Update Notably DG [View]
  docs/DeveloperGuide.adoc
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/UiClassDiagram.png
Labels: priority.High

#225 Update BlockModel DG
  docs/DeveloperGuide.adoc
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/TreeDataStructureDesign.puml
  docs/images/ModelClassDiagram.png
  docs/images/TreeDataStructureDesign.png
Labels: priority.High, status.Ongoing, type.Task

#226 Update Storage DG
  docs/DeveloperGuide.adoc
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: priority.High, status.Ongoing, type.Task

#232 Update Suggestion DG
  docs/DeveloperGuide.adoc
  docs/diagrams/SuggestionSequenceDiagram.puml
  docs/images/SuggestionClassDiagram.png
  docs/images/SuggestionSequenceDiagram.png
Labels: priority.High, status.Ongoing, type.Task

#185 Developer Guide (Logic)
  docs/DeveloperGuide.adoc
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/PathExample1.png
Labels: priority.Medium, status.Ongoing

#237 Update class diagram of SuggestionEngine
  docs/diagrams/SuggestionEngineClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/SuggestionClassDiagram.png
Labels: priority.High, status.Ongoing, type.Task

#214 Integrate correction engine
  src/main/java/com/notably/logic/LogicManager.java
  src/main/java/com/notably/logic/commands/NewCommand.java
  src/main/java/com/notably/logic/commands/OpenCommand.java
  src/main/java/com/notably/logic/parser/DeleteCommandParser.java
  src/main/java/com/notably/logic/parser/EditCommandParser.java
  src/main/java/com/notably/logic/parser/NewCommandParser.java
  src/main/java/com/notably/logic/parser/NotablyParser.java
  src/main/java/com/notably/logic/parser/OpenCommandParser.java
  src/main/java/com/notably/logic/parser/ParserUtil.java
  src/test/java/com/notably/logic/parser/NotablyParserTest.java
Labels: priority.High, type.Task

#239 Create DeleteSuggestionCommand and DeleteSuggestionCommandTest
  src/main/java/com/notably/logic/suggestion/commands/DeleteSuggestionCommand.java
  src/test/java/com/notably/logic/suggestion/commands/DeleteSuggestionCommandTest.java
Labels: priority.High, type.Enhancement

#243 Simplify com.notably.commons structure
  src/main/java/com/notably/AppParameters.java
  src/main/java/com/notably/MainApp.java
  src/main/java/com/notably/commons/Config.java
  src/main/java/com/notably/commons/GuiSettings.java
  src/main/java/com/notably/commons/LogsCenter.java
  src/main/java/com/notably/commons/Version.java
  src/main/java/com/notably/commons/index/Index.java
  src/main/java/com/notably/commons/path/AbsolutePath.java
  src/main/java/com/notably/commons/path/Path.java
  src/main/java/com/notably/commons/path/RelativePath.java
  src/main/java/com/notably/commons/path/exceptions/InvalidPathException.java
  src/main/java/com/notably/commons/util/ConfigUtil.java
  src/main/java/com/notably/commons/util/JsonUtil.java
  src/main/java/com/notably/logic/Logic.java
  src/main/java/com/notably/logic/LogicManager.java
  src/main/java/com/notably/logic/commands/DeleteCommand.java
  src/main/java/com/notably/logic/commands/NewCommand.java
  src/main/java/com/notably/logic/commands/OpenCommand.java
  src/main/java/com/notably/logic/correction/AbsolutePathCorrectionEngine.java
  src/main/java/com/notably/logic/parser/DeleteCommandParser.java
  src/main/java/com/notably/logic/parser/NewCommandParser.java
  src/main/java/com/notably/logic/parser/OpenCommandParser.java
  src/main/java/com/notably/logic/parser/ParserUtil.java
  src/main/java/com/notably/logic/suggestion/commands/DeleteSuggestionCommand.java
  src/main/java/com/notably/logic/suggestion/commands/OpenSuggestionCommand.java
  src/main/java/com/notably/model/Model.java
  src/main/java/com/notably/model/ModelManager.java
  src/main/java/com/notably/model/ReadOnlyUserPrefs.java
  src/main/java/com/notably/model/UserPrefs.java
  src/main/java/com/notably/model/block/BlockModel.java
  src/main/java/com/notably/model/block/BlockModelImpl.java
  src/main/java/com/notably/model/block/BlockTree.java
  src/main/java/com/notably/model/block/BlockTreeImpl.java
  src/main/java/com/notably/storage/JsonAddressBookStorage.java
  src/main/java/com/notably/storage/StorageManager.java
  src/main/java/com/notably/view/HelpWindow.java
  src/main/java/com/notably/view/MainWindow.java
  src/main/java/com/notably/view/ViewManager.java
  src/test/java/com/notably/commons/ConfigTest.java
  src/test/java/com/notably/commons/VersionTest.java
  src/test/java/com/notably/commons/index/IndexTest.java
  src/test/java/com/notably/commons/path/AbsolutePathTest.java
  src/test/java/com/notably/commons/path/RelativePathTest.java
  src/test/java/com/notably/commons/util/ConfigUtilTest.java
  src/test/java/com/notably/logic/LogicManagerTest.java
  src/test/java/com/notably/logic/correction/AbsolutePathCorrectionEngineTest.java
  src/test/java/com/notably/logic/parser/NotablyParserTest.java
  src/test/java/com/notably/logic/suggestion/commands/DeleteSuggestionCommandTest.java
  src/test/java/com/notably/logic/suggestion/commands/OpenSuggestionCommandTest.java
  src/test/java/com/notably/model/ModelManagerTest.java
  src/test/java/com/notably/model/block/BlockModelTest.java
  src/test/java/com/notably/model/block/BlockTreeTest.java
  src/test/java/com/notably/storage/JsonUserPrefsStorageTest.java
  src/test/java/com/notably/storage/StorageManagerTest.java
  src/test/java/com/notably/testutil/TypicalIndexes.java
Labels: priority.Medium, type.Task

#247 Fix bug in OpenSuggestionCommand
  src/main/java/com/notably/logic/suggestion/commands/OpenSuggestionCommand.java
  src/test/java/com/notably/logic/suggestion/commands/OpenSuggestionCommandTest.java
Labels: priority.High, type.Enhancement

#242 Create EditSuggestionCommand and EditSuggestionCommandTest
  src/main/java/com/notably/logic/suggestion/commands/EditSuggestionCommand.java
  src/test/java/com/notably/logic/suggestion/commands/EditSuggestionCommandTest.java
Labels: priority.High, type.Enhancement

#249 Rename distanceThreshold to DISTANCE_THRESHOLD
  src/main/java/com/notably/logic/parser/DeleteCommandParser.java
  src/main/java/com/notably/logic/parser/NotablyParser.java
  src/main/java/com/notably/logic/parser/OpenCommandParser.java
Labels: priority.Medium, type.Task

#251 Reorganise suggestion package
  src/main/java/com/notably/logic/commands/suggestion/DeleteSuggestionCommand.java
  src/main/java/com/notably/logic/commands/suggestion/EditSuggestionCommand.java
  src/main/java/com/notably/logic/commands/suggestion/ExitSuggestionCommand.java
  src/main/java/com/notably/logic/commands/suggestion/HelpSuggestionCommand.java
  src/main/java/com/notably/logic/commands/suggestion/NewSuggestionCommand.java
  src/main/java/com/notably/logic/commands/suggestion/OpenSuggestionCommand.java
  src/main/java/com/notably/logic/commands/suggestion/SuggestionCommand.java
  src/main/java/com/notably/logic/parser/suggestion/SuggestionCommandParser.java
  src/test/java/com/notably/logic/commands/suggestion/DeleteSuggestionCommandTest.java
  src/test/java/com/notably/logic/commands/suggestion/EditSuggestionCommandTest.java
  src/test/java/com/notably/logic/commands/suggestion/ExitSuggestionCommandTest.java
  src/test/java/com/notably/logic/commands/suggestion/HelpSuggestionCommandTest.java
  src/test/java/com/notably/logic/commands/suggestion/NewSuggestionCommandTest.java
  src/test/java/com/notably/logic/commands/suggestion/OpenSuggestionCommandTest.java
Labels: priority.High, type.Enhancement

#253 Create ErrorSuggestionCommand and ErrorSuggestionCommandTest
  src/main/java/com/notably/logic/commands/suggestion/ErrorSuggestionCommand.java
  src/test/java/com/notably/logic/commands/suggestion/ErrorSuggestionCommandTest.java
Labels: priority.High, type.Enhancement

#244 Implement Markdown to HTML compiler
  src/main/java/com/notably/commons/compiler/tokenizer/Token.java
  src/main/java/com/notably/commons/compiler/tokenizer/TokenType.java
  src/main/java/com/notably/commons/compiler/tokenizer/Tokenizer.java
  src/main/java/com/notably/commons/compiler/tokenizer/exceptions/UnknownTokenException.java
  src/main/java/com/notably/commons/compiler/tokenizer/rule/CarriageReturnRule.java
  src/main/java/com/notably/commons/compiler/tokenizer/rule/HashRule.java
  src/main/java/com/notably/commons/compiler/tokenizer/rule/LineFeedRule.java
  src/main/java/com/notably/commons/compiler/tokenizer/rule/MinusRule.java
  src/main/java/com/notably/commons/compiler/tokenizer/rule/Rule.java
  src/main/java/com/notably/commons/compiler/tokenizer/rule/SpaceRule.java
  src/main/java/com/notably/commons/compiler/tokenizer/rule/TextRule.java
  src/test/java/com/notably/commons/compiler/tokenizer/TokenizerTest.java
Labels: priority.High, type.Enhancement

#259 Improve sidebar to track both currently open note and do the 3-level display [View]
  src/main/java/com/notably/view/MainWindow.java
  src/main/java/com/notably/view/SideBarTreeView.java
  src/main/resources/view/SideBarTreeView.fxml
Labels: priority.High, type.Enhancement

#265 Enhance User Inferface for Notably [View]
  src/main/java/com/notably/commons/GuiSettings.java
  src/main/java/com/notably/view/CommandBox.java
  src/main/java/com/notably/view/HelpWindow.java
  src/main/java/com/notably/view/StatusBarFooter.java
  src/main/java/com/notably/view/ViewManager.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/NotablyTheme.css
  src/main/resources/view/SideBarTreeView.fxml
Labels: priority.High, type.Enhancement

#267 Bind CommandBox to CommandInputModel [View]
  src/main/java/com/notably/model/viewstate/ViewStateModelImpl.java
  src/main/java/com/notably/view/CommandBox.java
  src/main/java/com/notably/view/MainWindow.java
Labels: priority.High, type.Enhancement

#266 Revamp SuggestionItem and SuggestionItemImpl
  src/main/java/com/notably/model/suggestion/SuggestionItem.java
  src/main/java/com/notably/model/suggestion/SuggestionItemImpl.java
  src/test/java/com/notably/logic/commands/suggestion/DeleteSuggestionCommandTest.java
  src/test/java/com/notably/logic/commands/suggestion/OpenSuggestionCommandTest.java
Labels: priority.High, type.Enhancement

#257 Create SearchSuggestionCommand and SearchSuggestionCommandTest
  src/main/java/com/notably/logic/commands/suggestion/SearchSuggestionCommand.java
  src/test/java/com/notably/logic/commands/suggestion/SearchSuggestionCommandTest.java
Labels: priority.High, status.Ongoing, type.Enhancement

#240 Create OpenSuggestionCommandParser and OpenSuggestionCommandParserTest
  src/main/java/com/notably/logic/parser/suggestion/OpenSuggestionCommandParser.java
  src/test/java/com/notably/logic/parser/suggestion/OpenSuggestionCommandParserTest.java
  src/test/java/com/notably/logic/parser/suggestion/SuggestionCommandParserTestUtil.java
Labels: priority.High, type.Enhancement

#277 Revert "Implement Markdown to HTML compiler"
  src/main/java/com/notably/commons/compiler/tokenizer/Token.java
  src/main/java/com/notably/commons/compiler/tokenizer/TokenType.java
  src/main/java/com/notably/commons/compiler/tokenizer/Tokenizer.java
  src/main/java/com/notably/commons/compiler/tokenizer/exceptions/UnknownTokenException.java
  src/main/java/com/notably/commons/compiler/tokenizer/rule/CarriageReturnRule.java
  src/main/java/com/notably/commons/compiler/tokenizer/rule/HashRule.java
  src/main/java/com/notably/commons/compiler/tokenizer/rule/LineFeedRule.java
  src/main/java/com/notably/commons/compiler/tokenizer/rule/MinusRule.java
  src/main/java/com/notably/commons/compiler/tokenizer/rule/Rule.java
  src/main/java/com/notably/commons/compiler/tokenizer/rule/SpaceRule.java
  src/main/java/com/notably/commons/compiler/tokenizer/rule/TextRule.java
  src/test/java/com/notably/commons/compiler/tokenizer/TokenizerTest.java
Labels: priority.High, type.Task

#274 Create SuggestionEngineImpl
  src/main/java/com/notably/logic/commands/suggestion/DeleteSuggestionCommand.java
  src/main/java/com/notably/logic/commands/suggestion/EditSuggestionCommand.java
  src/main/java/com/notably/logic/commands/suggestion/ExitSuggestionCommand.java
  src/main/java/com/notably/logic/commands/suggestion/HelpSuggestionCommand.java
  src/main/java/com/notably/logic/commands/suggestion/NewSuggestionCommand.java
  src/main/java/com/notably/logic/commands/suggestion/OpenSuggestionCommand.java
  src/main/java/com/notably/logic/commands/suggestion/SearchSuggestionCommand.java
  src/main/java/com/notably/logic/suggestion/SuggestionEngine.java
  src/main/java/com/notably/logic/suggestion/SuggestionEngineImpl.java
  src/test/java/com/notably/logic/suggestion/SuggestionEngineImplTest.java
Labels: priority.High, status.Ongoing, type.Enhancement

#269 Implemented command shorthands
  src/main/java/com/notably/logic/commands/DeleteCommand.java
  src/main/java/com/notably/logic/commands/EditCommand.java
  src/main/java/com/notably/logic/commands/HelpCommand.java
  src/main/java/com/notably/logic/commands/NewCommand.java
  src/main/java/com/notably/logic/commands/OpenCommand.java
  src/main/java/com/notably/logic/parser/NotablyParser.java
  src/test/java/com/notably/logic/parser/NotablyParserTest.java
Labels: priority.Medium, type.Enhancement

#272 Implement optional prefix for commands
  src/main/java/com/notably/logic/parser/DeleteCommandParser.java
  src/main/java/com/notably/logic/parser/EditCommandParser.java
  src/main/java/com/notably/logic/parser/OpenCommandParser.java
  src/test/java/com/notably/logic/parser/NotablyParserTest.java
Labels: priority.Medium, type.Enhancement

#281 NewCommand optional body.
  src/main/java/com/notably/logic/parser/NewCommandParser.java
Labels: priority.High, type.Enhancement

#278 Implement partial Markdown to HTML compiler spec
  src/main/java/com/notably/commons/compiler/Compiler.java
  src/main/java/com/notably/commons/compiler/parser/Parser.java
  src/main/java/com/notably/commons/compiler/parser/block/Block.java
  src/main/java/com/notably/commons/compiler/parser/block/BlockUtil.java
  src/main/java/com/notably/commons/compiler/parser/block/DocumentBlock.java
  src/main/java/com/notably/commons/compiler/parser/block/HeaderBlock.java
  src/main/java/com/notably/commons/compiler/parser/block/ListBlock.java
  src/main/java/com/notably/commons/compiler/parser/block/ListItemBlock.java
  src/main/java/com/notably/commons/compiler/parser/block/ParagraphBlock.java
  src/main/java/com/notably/commons/compiler/parser/block/TextBlock.java
  src/main/java/com/notably/commons/compiler/parser/exceptions/InvalidLineException.java
  src/test/data/CompilerTest/Compiled.html
  src/test/data/CompilerTest/Markdown.md
  src/test/java/com/notably/commons/compiler/CompilerTest.java
Labels: priority.High, type.Enhancement

#279 Exception handling for parser
  src/main/java/com/notably/logic/commands/DeleteCommand.java
  src/main/java/com/notably/logic/commands/EditCommand.java
  src/main/java/com/notably/logic/commands/NewCommand.java
  src/main/java/com/notably/logic/commands/OpenCommand.java
  src/main/java/com/notably/logic/commands/suggestion/SearchSuggestionCommand.java
  src/main/java/com/notably/logic/parser/NotablyParser.java
  src/test/java/com/notably/logic/parser/NotablyParserTest.java
Labels: severity.High, type.Enhancement

#294 Wire up SuggestionEngine in LogicManager
  src/main/java/com/notably/logic/LogicManager.java
Labels: priority.High, type.Enhancement

#284 Update SuggestionCommands to accommodate optional prefix
  src/main/java/com/notably/logic/commands/suggestion/DeleteSuggestionCommand.java
  src/main/java/com/notably/logic/commands/suggestion/OpenSuggestionCommand.java
  src/main/java/com/notably/logic/parser/suggestion/OpenSuggestionCommandParser.java
  src/test/java/com/notably/logic/commands/suggestion/DeleteSuggestionCommandTest.java
  src/test/java/com/notably/logic/commands/suggestion/ErrorSuggestionCommandTest.java
  src/test/java/com/notably/logic/commands/suggestion/OpenSuggestionCommandTest.java
  src/test/java/com/notably/logic/parser/suggestion/OpenSuggestionCommandParserTest.java
  src/test/java/com/notably/logic/suggestion/SuggestionEngineImplTest.java
Labels: priority.High, type.Enhancement

#293 Implement BlockContentDisplayView
  build.gradle
  src/main/java/com/notably/view/BlockContentEditView.java
  src/main/java/com/notably/view/MainWindow.java
  src/main/java/com/notably/view/blockcontent/BlockContent.java
  src/main/java/com/notably/view/blockcontent/BlockContentDisplayView.java
  src/main/java/com/notably/view/blockcontent/BlockContentEditView.java
  src/main/resources/view/BlockContentEditView.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/blockcontent/BlockContentDisplayView.fxml
  src/main/resources/view/blockcontent/BlockContentEditView.fxml
Labels: priority.High, type.Enhancement

#303 Remove export command
  docs/UserGuide.adoc
  docs/images/Export.png
  docs/images/demo/Correction.png
  docs/images/demo/Delete1.png
  docs/images/demo/Delete2.png
  docs/images/demo/Edit1.png
  docs/images/demo/Edit2.png
  docs/images/demo/Exit.png
  docs/images/demo/Help.png
  docs/images/demo/New1.png
  docs/images/demo/New2.png
  docs/images/demo/New3.png
  docs/images/demo/Open.png
  docs/images/demo/Search.png
  docs/images/demo/Suggestions.png
Labels: priority.High, type.Task

#304 Revamp get possible paths
  src/main/java/com/notably/logic/commands/suggestion/DeleteSuggestionCommand.java
  src/main/java/com/notably/logic/commands/suggestion/OpenSuggestionCommand.java
  src/main/java/com/notably/logic/parser/suggestion/OpenSuggestionCommandParser.java
  src/test/java/com/notably/logic/commands/suggestion/DeleteSuggestionCommandTest.java
  src/test/java/com/notably/logic/commands/suggestion/OpenSuggestionCommandTest.java
  src/test/java/com/notably/logic/parser/suggestion/OpenSuggestionCommandParserTest.java
Labels: severity.High, status.Ongoing, type.Bug

#308 Clear sug and response text
  src/main/java/com/notably/logic/suggestion/SuggestionEngineImpl.java
  src/test/java/com/notably/logic/suggestion/SuggestionEngineImplTest.java
Labels: priority.High, type.Enhancement

#305 Userguide intro and path
  docs/UserGuide.adoc
  docs/images/IntroToNotably.png
  docs/images/PathExample1.png
Labels: priority.High, type.Task
